"""p1_9_kb_deletion_compensation_status

Revision ID: 1a4ff5a803d2
Revises: b74589b68f7d
Create Date: 2026-06-23 13:44:53.181100+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a4ff5a803d2'
down_revision: Union[str, Sequence[str], None] = 'b74589b68f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级到本版本：执行 schema 变更。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kb_files', sa.Column('cleanup_retry_count', sa.Integer(), server_default='0', nullable=False, comment='P1-9 待补偿清理重试次数；超过 CLEANUP_REAPER_MAX_RETRY 仅告警'))
    op.add_column('knowledge_bases', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='P1-9 行最后更新时间；pending_cleanup 扫描据此判定优先级'))
    op.add_column('knowledge_bases', sa.Column('cleanup_retry_count', sa.Integer(), server_default='0', nullable=False, comment='P1-9 待补偿清理重试次数；超过 CLEANUP_REAPER_MAX_RETRY 仅告警'))
    op.create_index(op.f('ix_knowledge_bases_updated_at'), 'knowledge_bases', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚本版本：撤销 upgrade() 所做的变更。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_bases_updated_at'), table_name='knowledge_bases')
    op.drop_column('knowledge_bases', 'cleanup_retry_count')
    op.drop_column('knowledge_bases', 'updated_at')
    op.drop_column('kb_files', 'cleanup_retry_count')
    # ### end Alembic commands ###
