"""baseline_v2

Revision ID: b74589b68f7d
Revises: 
Create Date: 2026-06-22 15:31:54.723140+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b74589b68f7d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级到本版本：执行 schema 变更。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kb_files', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='行最后更新时间；processing 文件的心跳锚点（卡死回收依据）'))
    op.create_index(op.f('ix_kb_files_updated_at'), 'kb_files', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚本版本：撤销 upgrade() 所做的变更。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kb_files_updated_at'), table_name='kb_files')
    op.drop_column('kb_files', 'updated_at')
    # ### end Alembic commands ###
